server:
  port: 8081

spring:
  application:
    name: auth-service

  resilience4j:
    circuitbreaker:
      instances:
        walletService:
          sliding-window-size: 5
          minimum-number-of-calls: 3
          failure-rate-threshold: 50
          wait-duration-in-open-state: 10s

  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: health, circuitbreakers
